// <auto-generated />
using LearningServer01.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningServer01.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260118102030_UdatePlayerSchema01")]
    partial class UdatePlayerSchema01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LearningServer01.PlayerInfo", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Food")
                        .HasColumnType("int");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SkillID01")
                        .HasColumnType("int");

                    b.Property<int>("SkillID02")
                        .HasColumnType("int");

                    b.Property<int>("SkillID03")
                        .HasColumnType("int");

                    b.Property<int>("SpellID01")
                        .HasColumnType("int");

                    b.Property<int>("SpellID02")
                        .HasColumnType("int");

                    b.Property<int>("SpellID03")
                        .HasColumnType("int");

                    b.Property<int>("Wood")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
