// <auto-generated />
using LearningServer01;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningServer01.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260120045846_RDBMS_Setup")]
    partial class RDBMS_Setup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LearningServer01.Data.StructureInfo", b =>
                {
                    b.Property<long>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("UID"));

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("OwnerID")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionY")
                        .HasColumnType("int");

                    b.Property<int>("PositionZ")
                        .HasColumnType("int");

                    b.Property<int>("RotationY")
                        .HasColumnType("int");

                    b.Property<uint>("TableID")
                        .HasColumnType("int unsigned");

                    b.HasKey("UID");

                    b.HasIndex("OwnerID");

                    b.ToTable("Structures");
                });

            modelBuilder.Entity("LearningServer01.PlayerInfo", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Food")
                        .HasColumnType("int");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SkillID01")
                        .HasColumnType("int");

                    b.Property<int>("SkillID02")
                        .HasColumnType("int");

                    b.Property<int>("SkillID03")
                        .HasColumnType("int");

                    b.Property<int>("SpellID01")
                        .HasColumnType("int");

                    b.Property<int>("SpellID02")
                        .HasColumnType("int");

                    b.Property<int>("SpellID03")
                        .HasColumnType("int");

                    b.Property<int>("Wood")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("LearningServer01.Data.StructureInfo", b =>
                {
                    b.HasOne("LearningServer01.PlayerInfo", "Owner")
                        .WithMany("Structures")
                        .HasForeignKey("OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("LearningServer01.PlayerInfo", b =>
                {
                    b.Navigation("Structures");
                });
#pragma warning restore 612, 618
        }
    }
}
