// <auto-generated />
using System;
using LearningServer01;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningServer01.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260312043618_BattleLogModify01")]
    partial class BattleLogModify01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LearningServer01.BattleLogInfo", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("AttackerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AttackerNickname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("BattleResult")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("DefenderId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DefenderNickname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsRevenged")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LogTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LootedFood")
                        .HasColumnType("int");

                    b.Property<int>("LootedGold")
                        .HasColumnType("int");

                    b.Property<int>("LootedWood")
                        .HasColumnType("int");

                    b.Property<byte>("ModeType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("AttackerId");

                    b.HasIndex("DefenderId");

                    b.ToTable("BattleLogs");
                });

            modelBuilder.Entity("LearningServer01.Data.DeploymentSlot", b =>
                {
                    b.Property<long>("SlotUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SlotUID"));

                    b.Property<long?>("EquippedItemUID")
                        .HasColumnType("bigint");

                    b.Property<string>("OwnerID")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SlotIdx")
                        .HasColumnType("int");

                    b.HasKey("SlotUID");

                    b.HasIndex("EquippedItemUID");

                    b.HasIndex("OwnerID");

                    b.ToTable("DeploymentSlots");
                });

            modelBuilder.Entity("LearningServer01.Data.EntityItemInfo", b =>
                {
                    b.Property<long>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("UID"));

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<bool>("NeedsRepair")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OwnerID")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<float>("PositionX")
                        .HasColumnType("float");

                    b.Property<float>("PositionZ")
                        .HasColumnType("float");

                    b.Property<float>("RotationY")
                        .HasColumnType("float");

                    b.Property<int>("TableID")
                        .HasColumnType("int");

                    b.HasKey("UID");

                    b.HasIndex("OwnerID");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("LearningServer01.EntityGarrisonInfo", b =>
                {
                    b.Property<long>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("UID"));

                    b.Property<long>("EquippedItemUID")
                        .HasColumnType("bigint");

                    b.Property<long>("OwnerEntityUID")
                        .HasColumnType("bigint");

                    b.Property<int>("SlotIdx")
                        .HasColumnType("int");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("UID");

                    b.HasIndex("OwnerEntityUID");

                    b.ToTable("EntityGarrisonInfo");
                });

            modelBuilder.Entity("LearningServer01.PlayerInfo", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Bounty")
                        .HasColumnType("int");

                    b.Property<long?>("EquippedHeroItemUID")
                        .HasColumnType("bigint");

                    b.Property<int>("Food")
                        .HasColumnType("int");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SkillID01")
                        .HasColumnType("int");

                    b.Property<int>("SkillID02")
                        .HasColumnType("int");

                    b.Property<int>("SkillID03")
                        .HasColumnType("int");

                    b.Property<int>("SpellID01")
                        .HasColumnType("int");

                    b.Property<int>("SpellID02")
                        .HasColumnType("int");

                    b.Property<int>("SpellID03")
                        .HasColumnType("int");

                    b.Property<string>("StatusMsg")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StrengthStat")
                        .HasColumnType("int");

                    b.Property<int>("Wood")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("LearningServer01.UserItem", b =>
                {
                    b.Property<long>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("UID"));

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("OwnerID")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TableID")
                        .HasColumnType("int");

                    b.HasKey("UID");

                    b.HasIndex("OwnerID");

                    b.ToTable("UserItems");
                });

            modelBuilder.Entity("LearningServer01.BattleLogInfo", b =>
                {
                    b.HasOne("LearningServer01.PlayerInfo", "AttackerPlayer")
                        .WithMany()
                        .HasForeignKey("AttackerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearningServer01.PlayerInfo", "DefenderPlayer")
                        .WithMany("BattleLogs")
                        .HasForeignKey("DefenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttackerPlayer");

                    b.Navigation("DefenderPlayer");
                });

            modelBuilder.Entity("LearningServer01.Data.DeploymentSlot", b =>
                {
                    b.HasOne("LearningServer01.UserItem", "EquippedItem")
                        .WithMany()
                        .HasForeignKey("EquippedItemUID");

                    b.HasOne("LearningServer01.PlayerInfo", "Owner")
                        .WithMany("DeploymentSlots")
                        .HasForeignKey("OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquippedItem");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("LearningServer01.Data.EntityItemInfo", b =>
                {
                    b.HasOne("LearningServer01.PlayerInfo", "Owner")
                        .WithMany("PlacedEntities")
                        .HasForeignKey("OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("LearningServer01.EntityGarrisonInfo", b =>
                {
                    b.HasOne("LearningServer01.Data.EntityItemInfo", "OwnerStructure")
                        .WithMany("Garrisons")
                        .HasForeignKey("OwnerEntityUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerStructure");
                });

            modelBuilder.Entity("LearningServer01.UserItem", b =>
                {
                    b.HasOne("LearningServer01.PlayerInfo", "Owner")
                        .WithMany("InventoryItems")
                        .HasForeignKey("OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("LearningServer01.Data.EntityItemInfo", b =>
                {
                    b.Navigation("Garrisons");
                });

            modelBuilder.Entity("LearningServer01.PlayerInfo", b =>
                {
                    b.Navigation("BattleLogs");

                    b.Navigation("DeploymentSlots");

                    b.Navigation("InventoryItems");

                    b.Navigation("PlacedEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
